<?xml version="1.0" encoding="utf-8"?><Database Name="MVCTest" Class="dataProductsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-889S9TQ;Initial Catalog=MVCTest;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MVCTestConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.spc_GetProducts" Method="spc_GetProducts">
    <ElementType Name="spc_GetProductsResult">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="ProductPrice" Type="System.Decimal" DbType="Decimal(22,4)" CanBeNull="true" />
      <Column Name="delete_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>